---
title: "Regression"
output: pdf_document
date: "2024-04-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
df <- read_csv("alleghenycounty_crashdata_2022.csv")
```

# Changing feature values from non-informative numbers to informative names

```{r}
df <- df %>%
  mutate(ROAD_CONDITION = factor(ROAD_CONDITION, 
                                 levels = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 98, 99),
                                 labels = c("Dry", "Wet", "Sand/mud/dirt/oil/gravel", 
                                            "Snow covered", "Slush", "Ice", "Ice Patches", 
                                            "Water - standing or moving", "Other", "Unknown (expired)", 
                                            "Other", "Unknown")),
         ILLUMINATION = factor(ILLUMINATION,
                               levels = c(1, 2, 3, 4, 5, 6, 8, 9),
                               labels = c("Daylight", "Dark – no street lights", 
                                          "Dark – street lights", "Dusk", "Dawn", 
                                          "Dark – unknown roadway lighting", "Other", "Other")),
         WEATHER = factor(WEATHER,
                          levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 98, 99),
                          labels = c("Blowing Sand, Soil, Dirt", "Blowing Snow", "Clear", 
                                     "Cloudy", "Fog, Smog, Smoke", "Freezing Rain or Freezing Drizzle", 
                                     "Rain", "Severe Crosswinds", "Sleet or Hail", "Snow", 
                                     "Other", "Unknown")),
         DARK=case_when(HOUR_OF_DAY>17 & HOUR_OF_DAY<6~1,TRUE~0),
         COLLISION_TYPE = factor(COLLISION_TYPE, levels = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
                                 labels = c("Non collision", "Rear-end", "Head-on", "Rear-to-rear (Backing)",
                                            "Angle", "Sideswipe (same dir.)", "Sideswipe (Opposite dir.)",
                                            "Hit fixed object", "Hit pedestrian", "Other or Unknown")),
         LOCATION_TYPE = factor(LOCATION_TYPE,levels = c("00", "01", "02", "03", "04", "05", "06", "07", "08", "99"),
                                                labels = c("Not applicable", "Underpass", "Ramp", "Bridge", "Tunnel",
                                                           "Toll Booth", "Cross over related", "Driveway or Parking Lot",
                                                           "Ramp and bridge", "Unknown")),
         INTERSECT_TYPE = factor(INTERSECT_TYPE,
                                        levels = c("00", "01", "02", "03", "04", "05", 
                                                   "06", "07", "08", "09", "10", "99", 
                                                   "11", "12", "13"),
                                        labels = c("Mid-block", 
                                                   "Four way intersection", 
                                                   "T intersection", 
                                                   "Y intersection", 
                                                   "Traffic circle or Round About", 
                                                   "Multi-leg intersection", 
                                                   "On ramp", 
                                                   "Off ramp", 
                                                   "Crossover", 
                                                   "Railroad crossing", 
                                                   "Other", 
                                                   "Unknown (expired)",
                                                   "Type 11 Description", 
                                                   "Type 12 Description", 
                                                   "Type 13 Description")),
         ROAD_OWNER = factor(ROAD_OWNER,
                             levels = c(1, 2, 3, 4, 5, 6, 7, 9),
                             labels = c("Interstate - non turnpike", 
                                        "State highway", 
                                        "County road", 
                                        "Local road or street", 
                                        "East-West portion of turnpike", 
                                        "Turnpike spur (extension)", 
                                        "Private Road", 
                                        "Other or Unknown"))
         )
```


# Regression with single features

```{r}
model.1 <- glm(INJURY_OR_FATAL ~ ILLUMINATION, family=binomial, data=df)
summary(model.1)

model.2 <- glm(INJURY_OR_FATAL ~ ROAD_CONDITION, family=binomial, data=df)
summary(model.2)

model.3 <- glm(INJURY_OR_FATAL ~ AGGRESSIVE_DRIVING, family=binomial, data=df)
summary(model.3)

model.4 <- glm(INJURY_OR_FATAL ~ LOCATION_TYPE, family=binomial, data=df)
summary(model.4)

model.5 <- glm(INJURY_OR_FATAL ~ UNBELTED, family=binomial, data=df)
summary(model.5)

model.6 <- glm(INJURY_OR_FATAL ~ DISTRACTED, family=binomial, data=df)
summary(model.6)

model.7 <- glm(INJURY_OR_FATAL ~ CURVED_ROAD, family=binomial, data=df)
summary(model.7)

model.8 <- glm(INJURY_OR_FATAL ~ IMPAIRED_DRIVER, family=binomial, data=df)
summary(model.8)

model.9 <- glm(INJURY_OR_FATAL ~ ROAD_OWNER, family=binomial, data=df)
summary(model.9)

model.10 <- glm(INJURY_OR_FATAL ~ SPEED_LIMIT, family=binomial, data=df)
summary(model.10)

model.11 <- glm(INJURY_OR_FATAL ~ MUNICIPALITY, family=binomial, data=df)
summary(model.11)

model.12 <- glm(INJURY_OR_FATAL ~ SCHOOL_ZONE, family=binomial, data=df)
summary(model.12)

model.13 <- glm(INJURY_OR_FATAL ~ WEATHER, family=binomial, data=df)
summary(model.13)
```

# Multiple regression (INJURY_OR_FATAL)
```{r}
model.14 <- glm(INJURY_OR_FATAL ~
                 ILLUMINATION+ROAD_CONDITION+AGGRESSIVE_DRIVING+LOCATION_TYPE+UNBELTED+
                 DISTRACTED+CURVED_ROAD+IMPAIRED_DRIVER+ROAD_OWNER+SPEED_LIMIT+MUNICIPALITY+
                 SCHOOL_ZONE+WEATHER, family=binomial, data=df)
summary(model.14)
```


# Lasso Regularization (INJURY_OR_FATAL)
```{r}
library(glmnet)
df_lasso = df[c("INJURY_OR_FATAL","ILLUMINATION","ROAD_CONDITION","AGGRESSIVE_DRIVING",
                "LOCATION_TYPE","DISTRACTED","CURVED_ROAD","UNBELTED","IMPAIRED_DRIVER",
                "ROAD_OWNER","SPEED_LIMIT","MUNICIPALITY","SCHOOL_ZONE","WEATHER")]
df_lasso_no_NAN = na.omit(df_lasso)

X <- model.matrix(INJURY_OR_FATAL ~ ., data = df_lasso_no_NAN)
Y <- as.numeric(df_lasso_no_NAN$INJURY_OR_FATAL)

lasso.model <- cv.glmnet(X, Y, alpha = 1)
lasso.coef <- coef(lasso.model, s = "lambda.min")
print(lasso.coef)
```

# Multiple regression (FATAL_OR_MAJ_INJ)
```{r}
model.15 <- glm(FATAL_OR_MAJ_INJ ~
                 ILLUMINATION+ROAD_CONDITION+AGGRESSIVE_DRIVING+LOCATION_TYPE+UNBELTED+
                 DISTRACTED+CURVED_ROAD+IMPAIRED_DRIVER+ROAD_OWNER+SPEED_LIMIT+MUNICIPALITY+
                 SCHOOL_ZONE+WEATHER, family=binomial, data=df)
summary(model.15)
```

# Lasso Regularization (FATAL_OR_MAJ_INJ)
```{r}
library(glmnet)
df_lasso = df[c("FATAL_OR_MAJ_INJ","ILLUMINATION","ROAD_CONDITION","AGGRESSIVE_DRIVING",
                "LOCATION_TYPE","DISTRACTED","CURVED_ROAD","UNBELTED","IMPAIRED_DRIVER",
                "ROAD_OWNER","SPEED_LIMIT","MUNICIPALITY","SCHOOL_ZONE","WEATHER")]
df_lasso_no_NAN = na.omit(df_lasso)

X <- model.matrix(FATAL_OR_MAJ_INJ ~ ., data = df_lasso_no_NAN)
Y <- as.numeric(df_lasso_no_NAN$FATAL_OR_MAJ_INJ)

lasso.model <- cv.glmnet(X, Y, alpha = 1)
lasso.coef <- coef(lasso.model, s = "lambda.min")
print(lasso.coef)
```